### ISSUE TITLE
Write tests to make sure glados is validating content correctly

### ISSUE THREAD

**Issue by KolbyML** [ethereum/glados#157]
Currently we have a high success rate on our testnet, but glados has a bug where it says the audit failed. But we can see in the trace that it did find the content.

![image](https://github.com/ethereum/glados/assets/31669092/9996a6cd-01c2-4220-9267-c2bca890d39a)

^ here is a picture (the green bubble is that we found the content)

The reason we want this test is so if we are updating library versions we know that the code will still pass. We want to catch the bug before at the PR stage to prevent headache and to ensure we know it is a issue with the network not glados itself.

**Comment by mrferris** [comment]
As mentioned in discord, this is caused by a utp failure after the content is found, not glados validation.

But to your initial point, this same effect used to happen when glados failed to "validate content correctly", which isn't really validation, it's just decoding using `ethportal_api`. I'm not sure why `ethportal_api`'s tests weren't catching that issue (maybe incorrect/out of date test vectors), but those tests should be expanded improved in that crate rather than made redundant within glados as well.
